### PR TITLE
Add ifq grouping

### PR DESCRIPTION
**Pull request by jimfellows-NOAA**
Creating new common model used to take either taxonomy/catch grouping and translate to IFQ management grouping based on the location and year caught.

### CODE REVIEW

**Comment by wsmith-nwfsc** [comment]
I missed this PR. We need to review briefly to make sure it's still valid (If it's already published, free to merge and delete this branch)

**Comment by jimfellows-NOAA** [comment]
Open to review anytime.  Not sure what you mean by published, but the only changes here are adding two new interfaces, so impact to other branches / workflows should be minimal.

**Comment by jimfellows-NOAA** [comment]
conflict on index.ts resolved.  New files shouldn't have much impact, merging request.

**Comment by wsmith-nwfsc** [comment]
Looks good to merge. 
To publish on NPM, either you another teammate like @melinashak-noaa @SaOgaz-NOAA @sethgerou-noaa can help you do it, as   shown here: https://github.com/nwfsc-fram/boatnet-module/blob/master/CONTRIBUTING.md

**Pull request merged**
